[username]
show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false
format =  "@[$hostname](bold blue) "

[directory]
truncation_length = 10
truncate_to_repo = false
repo_root_style = "bold"

[custom.tlp]
command = 'echo TLP:RED'
style = 'bold red'
detect_files = ['tlp.red']
format = '[$output]($style)'
